### ISSUE TITLE
Integrate with EDD New Emails

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-admin-emails#1]
In the New Sale notification email and the Purchase receipt, we need to provide a template tag for booking details.

The admin can set the content of the email from the below relative site URL:

```
/wp-admin/edit.php?post_type=download&page=edd-settings&tab=emails&section=sale_notifications
```

The booking details template tag should display the following details:

- Service Booked (with link to service)
- Start Date and Time of Booking
- End Date and Time of Booking
- If timezone of client is different to timezone of the service, show start and end time and date in the client's timezone

**Comment by markzahra** [comment]
@mecha the details to show with the template tag that are listed in the description above could change if the other EDD tags already handle them, especially with things like service name.
